### ISSUE TITLE
Non compatibile con FreeBSD sed

### ISSUE THREAD

**Issue by gipert** [CloudPadovana/ECM#1]
Un dettaglio: ho notato che `ecm.py` non è compatibile con l'implementazione FreeBSD di `sed` (come si trova ad esempio in una distribuzione standard Apple). Basterebbe il cambio
```bash
sed -i ---> sed -i.bak
```
per rendere lo script compatibile con FreeBSD e GNU `sed`.

Ciao

**Comment by MatteoSegatta** [comment]
Grazie per avermelo fatto notare. Ho implementato la modifica e fatto il commit.
